module_name: Block New Products
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - products
  - marketing
  - new products
  - advertising
description_short: The block new products allows you to display new products to your customers.
description: description.md
images:
  - image-1.png
gdpr_compliant: true
license: AFL